apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: app-config
  namespace: todo-app
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.default:9411/api/v2/spans"
  metric:
    enabled: true
  httpPipeline:
    handlers:
    - name: uppercase
      type: middleware.http.uppercase
  features:
    - name: service.invocation.forwarding
      enabled: true
  secrets:
    scopes:
    - storeName: "kubernetes"
      defaultAccess: "allow"
      allowedSecrets:
      - "todo-secrets"
      - "postgres-secret"
      - "kafka-secret"